name: rad_video_player_platform_interface
description: A common platform interface for the video_player plugin.
repository: https://github.com/radocc/rad_video_player_platform_interface
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  pedantic: ^1.10.0
